### ISSUE TITLE
Replace KimonoLabs with WordPress.org API

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/WordPress.org-Reviews#2]
It would be possible to use [WordPress.org API](http://codex.wordpress.org/WordPress.org_API) instead of KimonoLabs.

As this API doesn't return formatted data (JSON, XML), but HTML markup + data, we would have to parse the output. We could use *Simple HTML DOM Library*: http://code.tutsplus.com/tutorials/html-parsing-and-screen-scraping-with-the-simple-html-dom-library--net-11856

## Pros

* Should be quicker (as we query WordPress.org right away)
* No API limits? To be confirmed
* Does not rely on an external service

## Cons

* Requires to parse the output

**Comment by julien731** [comment]
Done da2c8fbf8abb5a4331f1489c536824d3061e56fa
